version: "3.8"
services:
  vuejs:
    build: ./front
    ports:
     - "8080:8080"
    container_name: vuejs_c
    depends_on:
      - nestjs
    networks:
      - internal
    volumes:
      - type: bind
        source: ./front/src
        target: /usr/src/app/front/src
    restart: unless-stopped
    command: npm run serve
  postgres:
    image: postgres
    container_name: postgres_c
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - type: bind
        source: ./db
        target: /usr/src/app/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - internal
    ports: 
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
  nestjs:
    build: ./back
    depends_on: 
      - postgres
    ports:
      - "3000:3000"
    container_name: nestjs_c
    volumes:
      - type: bind
        source: ./back/src
        target: /usr/src/app/back/src
    restart: unless-stopped
    command: npm run start:migrate:dev
    networks: 
     - internal
networks: 
  internal:
    driver: bridge

