version: "3.8"
services:
  vuejs:
    build: ./front
    ports:
      - "8080:8080"
    container_name: vuejs_c
    depends_on:
      - nestjs
    networks:
      - internal
    volumes:
      - type: bind
        source: ./front
        target: /usr/src/app/front
    restart: unless-stopped
    command: npm run serve
  postgres:
    image: postgres
    container_name: postgres_c
    restart: unless-stopped
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - type: bind
        source: ./db
        target: /usr/src/app/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  nestjs:
    build:
      context: ./back
    tty: true ##
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "5555:5555"
    container_name: nestjs_c
    # environment:
    #   - GOOGLE_OAUTH_CS=${GOOGLE_OAUTH_CS}
    #   - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
    volumes:
      - type: bind
        source: ./back
        target: /usr/src/app/back


    restart: unless-stopped
    command: npm run start:dbpush:dev
    networks:
      - internal
networks:
  internal:
    driver: bridge
