### Insert a New User

PUT  http://localhost:3000/api/users/create
content-type: application/json

{
    "email": "alexandreb@unique-paris.fr",
    "name": "Alexandre BESOMBES"
}

### Insert a New User

POST  http://localhost:3000/api/users/create-user
content-type: application/json

{
    "email": "vanessa@unique-paris.fr",
    "name": "Vanessa ZAPATA"
}

### Fetch All Users
GET http://localhost:3000/api/fetch-users


### Fetch One Specific User
GET http://localhost:3000/api/fetch-user/2

### Delete One Specific User
DELETE http://localhost:3000/api/delete-user/1


### Auth - Local Signup

POST http://localhost:3000/auth/local/signup