### Insert a New User

PUT  http://localhost:3000/api/users/create
content-type: application/json

{
    "email": "alexandreb@unique-paris.fr",
    "name": "Alexandre BESOMBES"
}

### Insert a New User

POST  http://localhost:3000/api/users/create-user
content-type: application/json

{
    "email": "vanessa@unique-paris.fr",
    "name": "Vanessa ZAPATA"
}

### Fetch All Users
GET http://localhost:3000/api/fetch-users


### Fetch One Specific User
GET http://localhost:3000/api/fetch-user/2

### Delete One Specific User
DELETE http://localhost:3000/api/delete-user/1


### Auth - Local Signup

POST http://localhost:3000/auth/local/signup
content-type: application/json

{
    "email": "test3@gmail.com",
    "nickname": "Alphaboy",
    "password": "12345abcde"
}

### Auth - Local Signin

POST http://localhost:3000/auth/local/signin
content-type: application/json

{
    "email": "test3@gmail.com",
    "nickname": "Alphaboy",
    "password": "12345abcde"
}

### Auth - Logout

POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNGIwYzIyMC1lNzliLTRiZGYtYWM2Ny1hYmM0MDliZDk4YTYiLCJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE0MjY0MSwiZXhwIjoxNjY0MTQzNTQxfQ.O_dJsdl8Qqq8lYbIglMgnDtvU95VydnSqBOlEi1lO7c

### Auth - Refresh

POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNGIwYzIyMC1lNzliLTRiZGYtYWM2Ny1hYmM0MDliZDk4YTYiLCJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE0NTY2MiwiZXhwIjoxNjY0NzUwNDYyfQ.5kb-XYjfmh2hrac84mEh8O2HuvzDmxza2zYOMVRGIfE
