### Insert a New User

PUT  http://localhost:3000/api/users/create
content-type: application/json

{
    "email": "alexandreb@unique-paris.fr",
    "name": "Alexandre BESOMBES"
}

### Insert a New User

POST  http://localhost:3000/api/users/create-user
content-type: application/json

{
    "email": "vanessa@unique-paris.fr",
    "name": "Vanessa ZAPATA"
}

### Fetch All Users
GET http://localhost:3000/api/fetch-users


### Fetch One Specific User
GET http://localhost:3000/api/fetch-user/2

### Delete One Specific User
DELETE http://localhost:3000/api/delete-user/1


### Auth - Local Signup

POST http://localhost:3000/auth/local/signup
content-type: application/json

{
    "email": "test4@gmail.com",
    "nickname": "Alphaboy4",
    "password": "12345abcde"
}

### Auth - Local Signin

POST http://localhost:3000/auth/local/signin
content-type: application/json

{
    "email": "test4@gmail.com",
    "nickname": "Alphaboy4",
    "password": "12345abcde"
}

### Auth - Logout

POST http://localhost:3000/auth/logout
Host: localhost
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWE4MDM3MS0zODY5LTQ3NjktYmQwNS04Nzc3OWRiNzQ5OTUiLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY2NDc5ODI5NCwiZXhwIjoxNjY1NDAzMDk0fQ.GfnsCyuhtP67VQEUMtju1UsuL6s0zvLXVyde1sJggJU

### Auth - Refresh

POST http://localhost:3000/auth/refresh
Host: localhost
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWE4MDM3MS0zODY5LTQ3NjktYmQwNS04Nzc3OWRiNzQ5OTUiLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY2NDc5ODI5NCwiZXhwIjoxNjY1NDAzMDk0fQ.GfnsCyuhtP67VQEUMtju1UsuL6s0zvLXVyde1sJggJU



### Test Request to Marvin
GET https://api.intra.42.fr/oauth/authorize?client_id=42a3b64eee675b3850058c804e485115de4a51ddc88cc1c76f093f17d48568ee&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fmarvin%2Fcallback&response_type=code


### Test 2FA Authentication Turn-On After Login

POST http://localhost:3000/auth/2fa/turn-on
Host: localhost
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWE4MDM3MS0zODY5LTQ3NjktYmQwNS04Nzc3OWRiNzQ5OTUiLCJlbWFpbCI6InRlc3Q0QGdtYWlsLmNvbSIsImlhdCI6MTY2NDgwNjQ5NiwiZXhwIjoxNjY0ODA3Mzk2fQ.wFC-jzCH9Xk89tLRumaCjZ8tUJcfD8mlTvkwUYLd55w

{
    "twoFactorAuthCode": "dhgdhf"
}